name: First Github action
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node_modules
        run: npm install -g node-modules
      - name: Bouil the project
        run: npm build
      - run: echo "setup finished"